//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Z_Cancel {
            get {
                return ResourceManager.GetString("Z.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose first.
        /// </summary>
        public static string Z_Config_Behavior_ChooseFirst {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ChooseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z will choose first result in suggestions window and perform its action. If there are no suggestions, nothing will happen..
        /// </summary>
        public static string Z_Config_Behavior_ChooseFirst_Comment {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ChooseFirst_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose perfectly matched.
        /// </summary>
        public static string Z_Config_Behavior_ChoosePerfectlyMatched {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ChoosePerfectlyMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z will try to find perfect match for entered text among modules. If there&apos;s only one, it will be executed. If there are more, you will be asked, which one do you want to execute..
        /// </summary>
        public static string Z_Config_Behavior_ChoosePerfectlyMatched_Comment {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ChoosePerfectlyMatched_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter key behavior.
        /// </summary>
        public static string Z_Config_Behavior_EnterBehavior_Label {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_EnterBehavior_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose, what happens, when you press Enter key .
        /// </summary>
        public static string Z_Config_Behavior_EnterCommentLine1 {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_EnterCommentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when no suggestion is selected and no keyword is used.
        /// </summary>
        public static string Z_Config_Behavior_EnterCommentLine2 {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_EnterCommentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string Z_Config_Behavior_EnterCommentLine3 {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_EnterCommentLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing actions.
        /// </summary>
        public static string Z_Config_Behavior_ExecutingActions {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ExecutingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Z_Config_Behavior_Ms {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell execute.
        /// </summary>
        public static string Z_Config_Behavior_ShellExecute {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ShellExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the Z window to behave as Start | Run. When you press Enter, Z will try to execute entered text as command..
        /// </summary>
        public static string Z_Config_Behavior_ShellExecute_Comment {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_ShellExecute_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by match.
        /// </summary>
        public static string Z_Config_Behavior_SortByMatch {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SortByMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by module.
        /// </summary>
        public static string Z_Config_Behavior_SortByModule {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SortByModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by title.
        /// </summary>
        public static string Z_Config_Behavior_SortByTitle {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion delay.
        /// </summary>
        public static string Z_Config_Behavior_SuggestionDelay {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SuggestionDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How soon should suggestion window appear, when you stop typing..
        /// </summary>
        public static string Z_Config_Behavior_SuggestionDelay_Comment {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SuggestionDelay_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Z_Config_Behavior_Suggestions_Label {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_Suggestions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion sorting.
        /// </summary>
        public static string Z_Config_Behavior_SuggestionSorting {
            get {
                return ResourceManager.GetString("Z_Config_Behavior_SuggestionSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Z_Config_General_Alt {
            get {
                return ResourceManager.GetString("Z_Config_General_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Z_Config_General_Control {
            get {
                return ResourceManager.GetString("Z_Config_General_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose global shortcut to bring the Z window to the front.
        /// </summary>
        public static string Z_Config_General_GlobalShortcut {
            get {
                return ResourceManager.GetString("Z_Config_General_GlobalShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use hotkey again to hide window.
        /// </summary>
        public static string Z_Config_General_HotkeySwitchesVisibility {
            get {
                return ResourceManager.GetString("Z_Config_General_HotkeySwitchesVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey switches visibility.
        /// </summary>
        public static string Z_Config_General_HotkeySwitchesVisibility_Label {
            get {
                return ResourceManager.GetString("Z_Config_General_HotkeySwitchesVisibility_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Z_Config_General_Key {
            get {
                return ResourceManager.GetString("Z_Config_General_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Z_Config_General_Modifiers {
            get {
                return ResourceManager.GetString("Z.Config.General.Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Z_Config_General_Shift {
            get {
                return ResourceManager.GetString("Z_Config_General_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Z_Config_General_Shortcut {
            get {
                return ResourceManager.GetString("Z.Config.General.Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProCalc window position will be synchronized with Z window.
        /// </summary>
        public static string Z_Config_General_SynchronizeWindowPositions {
            get {
                return ResourceManager.GetString("Z_Config_General_SynchronizeWindowPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize window positions.
        /// </summary>
        public static string Z_Config_General_SynchronizeWindowPositions_Label {
            get {
                return ResourceManager.GetString("Z_Config_General_SynchronizeWindowPositions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Z_Config_Keyword_Action {
            get {
                return ResourceManager.GetString("Z_Config_Keyword_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Z_Config_Keyword_Keyword {
            get {
                return ResourceManager.GetString("Z_Config_Keyword_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Z_Config_Keyword_Keywords {
            get {
                return ResourceManager.GetString("Z_Config_Keyword_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Z_Config_Keyword_Module {
            get {
                return ResourceManager.GetString("Z_Config_Keyword_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Z_Config_Keyword_Override {
            get {
                return ResourceManager.GetString("Z_Config_Keyword_Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Z_Config_Launcher_Browse {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Z_Config_Launcher_Command {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find automatically.
        /// </summary>
        public static string Z_Config_Launcher_FindAutomatically {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_FindAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Z_Config_Launcher_Icon {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string Z_Config_Launcher_Launcher {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Z_Config_Launcher_Name {
            get {
                return ResourceManager.GetString("Z_Config_Launcher_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure....
        /// </summary>
        public static string Z_Config_Modules_Configure {
            get {
                return ResourceManager.GetString("Z_Config_Modules_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Z_Config_Modules_Module {
            get {
                return ResourceManager.GetString("Z_Config_Modules_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Z_Config_Modules_Modules {
            get {
                return ResourceManager.GetString("Z_Config_Modules_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Z_ConfigurationPage_Behavior {
            get {
                return ResourceManager.GetString("Z_ConfigurationPage_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Z_ConfigurationPage_General {
            get {
                return ResourceManager.GetString("Z_ConfigurationPage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Z_ConfigurationPage_Keywords {
            get {
                return ResourceManager.GetString("Z_ConfigurationPage_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string Z_ConfigurationPage_Launcher {
            get {
                return ResourceManager.GetString("Z_ConfigurationPage_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Z_ConfigurationPage_Modules {
            get {
                return ResourceManager.GetString("Z_ConfigurationPage_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        public static string Z_DefaultDialogTitle {
            get {
                return ResourceManager.GetString("Z_DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string Z_DefaultFilter {
            get {
                return ResourceManager.GetString("Z_DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application.
        /// </summary>
        public static string Z_DialogTitle_ChooseApplication {
            get {
                return ResourceManager.GetString("Z_DialogTitle_ChooseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose icon.
        /// </summary>
        public static string Z_DialogTitle_ChooseIcon {
            get {
                return ResourceManager.GetString("Z_DialogTitle_ChooseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Z_DialogTitle_Configuration {
            get {
                return ResourceManager.GetString("Z_DialogTitle_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications (*.exe)|*.exe|All files (*.*)|*.*.
        /// </summary>
        public static string Z_Filter_Application {
            get {
                return ResourceManager.GetString("Z_Filter_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported files (*.ico, *.exe)|*.ico;*.exe.
        /// </summary>
        public static string Z_Filter_IconFiles {
            get {
                return ResourceManager.GetString("Z_Filter_IconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Z_HelpModule_ModuleDisplayName {
            get {
                return ResourceManager.GetString("Z_HelpModule_ModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string Z_LauncherBreadcrumbsRoot {
            get {
                return ResourceManager.GetString("Z_LauncherBreadcrumbsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Z_Main_Context_Close {
            get {
                return ResourceManager.GetString("Z.Main.Context.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Z_Main_Context_Configuration {
            get {
                return ResourceManager.GetString("Z.Main.Context.Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+C or F3.
        /// </summary>
        public static string Z_Main_Context_SwitchToProCalcShortcut {
            get {
                return ResourceManager.GetString("Z.Main.Context.SwitchToProCalcShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+Z or F1.
        /// </summary>
        public static string Z_Main_Context_SwitchToZShortcut {
            get {
                return ResourceManager.GetString("Z.Main.Context.SwitchToZShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ? to get list of keywords. Press up for launcher..
        /// </summary>
        public static string Z_Main_Hint {
            get {
                return ResourceManager.GetString("Z.Main.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute: {0}.
        /// </summary>
        public static string Z_Message_CannotExecute {
            get {
                return ResourceManager.GetString("Z_Message_CannotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve icon automatically. Choose icon manually..
        /// </summary>
        public static string Z_Message_CouldNotResolveIconAutomatically {
            get {
                return ResourceManager.GetString("Z_Message_CouldNotResolveIconAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract icon from selected file!.
        /// </summary>
        public static string Z_Message_FailedToExtractIconFromSelectedFile {
            get {
                return ResourceManager.GetString("Z_Message_FailedToExtractIconFromSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open shortcut: {0}.
        /// </summary>
        public static string Z_Message_FailedToOpenShortcut {
            get {
                return ResourceManager.GetString("Z_Message_FailedToOpenShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module &quot;{0}&quot; reports error:
        /// {1}
        /// 
        ///Use module configuration to fix it or cancel your changes..
        /// </summary>
        public static string Z_Message_ModuleReportsError {
            get {
                return ResourceManager.GetString("Z_Message_ModuleReportsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type. Try .exe or .ico file..
        /// </summary>
        public static string Z_Message_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Z_Message_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z launcher is already running!.
        /// </summary>
        public static string Z_Message_ZLauncherIsAlreadyRunning {
            get {
                return ResourceManager.GetString("Z_Message_ZLauncherIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Z_OK {
            get {
                return ResourceManager.GetString("Z.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string Z_ProCalc_Bin {
            get {
                return ResourceManager.GetString("Z_ProCalc_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS.
        /// </summary>
        public static string Z_ProCalc_DMS {
            get {
                return ResourceManager.GetString("Z_ProCalc_DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expression to evaluate.
        /// </summary>
        public static string Z_ProCalc_EnterExpressionToEvaluate {
            get {
                return ResourceManager.GetString("Z_ProCalc_EnterExpressionToEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction.
        /// </summary>
        public static string Z_ProCalc_Fraction {
            get {
                return ResourceManager.GetString("Z_ProCalc_Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string Z_ProCalc_Hex {
            get {
                return ResourceManager.GetString("Z_ProCalc_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Z_ProCalc_Oct {
            get {
                return ResourceManager.GetString("Z_ProCalc_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple suggestions match, choose one below:.
        /// </summary>
        public static string Z_Suggestions_MultipleSuggestionsMatch {
            get {
                return ResourceManager.GetString("Z_Suggestions_MultipleSuggestionsMatch", resourceCulture);
            }
        }
    }
}
