//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FavoritesModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FavoritesModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access favorite places or websites.
        /// </summary>
        internal static string Favorites_ActionComment {
            get {
                return ResourceManager.GetString("Favorites_ActionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorites_ActionDisplay {
            get {
                return ResourceManager.GetString("Favorites_ActionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Favorites_Config_Add {
            get {
                return ResourceManager.GetString("Favorites_Config_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Favorites_Config_Comment {
            get {
                return ResourceManager.GetString("Favorites_Config_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Favorites_Config_Delete {
            get {
                return ResourceManager.GetString("Favorites_Config_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites_Config_Favorites {
            get {
                return ResourceManager.GetString("Favorites_Config_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (key).
        /// </summary>
        internal static string Favorites_Config_Name {
            get {
                return ResourceManager.GetString("Favorites_Config_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Favorites_Config_OK {
            get {
                return ResourceManager.GetString("Favorites_Config_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place or URL.
        /// </summary>
        internal static string Favorites_Config_PlaceOrURL {
            get {
                return ResourceManager.GetString("Favorites_Config_PlaceOrURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute: {0}.
        /// </summary>
        internal static string Favorites_Message_CannotExecute {
            get {
                return ResourceManager.GetString("Favorites_Message_CannotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite names must be unique!.
        /// </summary>
        internal static string Favorites_Message_FavoriteNamesMustBeUnique {
            get {
                return ResourceManager.GetString("Favorites_Message_FavoriteNamesMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites_ModuleDisplayName {
            get {
                return ResourceManager.GetString("Favorites_ModuleDisplayName", resourceCulture);
            }
        }
    }
}
