//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filesystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filesystem.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse through the filesystem.
        /// </summary>
        internal static string Filesystem_ActionComment {
            get {
                return ResourceManager.GetString("Filesystem_ActionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Filesystem_ActionDisplayName {
            get {
                return ResourceManager.GetString("Filesystem_ActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep.
        /// </summary>
        internal static string Filesystem_Config_Deep {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strategy searches through all matching directories on all levels, so for input.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment1 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\W\S\x.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment2 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will search for.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment3 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\*W*\*S*\*x*.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment4 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so it will find, for example,.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment5 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\System32\x3daudio1_0.dll.
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment6 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment7 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This strategy is slower, but yields more results and simplifies the search..
        /// </summary>
        internal static string Filesystem_Config_Deep_Comment8 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Deep_Comment8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        internal static string Filesystem_Config_Direct {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strategy assumes, that path exists, so for input.
        /// </summary>
        internal static string Filesystem_Config_Direct_Comment1 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct_Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\W\S\x.
        /// </summary>
        internal static string Filesystem_Config_Direct_Comment2 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct_Comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will search for.
        /// </summary>
        internal static string Filesystem_Config_Direct_Comment3 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct_Comment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\W\S\*x*.
        /// </summary>
        internal static string Filesystem_Config_Direct_Comment4 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct_Comment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This strategy is faster, but yields less results..
        /// </summary>
        internal static string Filesystem_Config_Direct_Comment5 {
            get {
                return ResourceManager.GetString("Filesystem_Config_Direct_Comment5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search strategy.
        /// </summary>
        internal static string Filesystem_Config_FileSearchStrategy {
            get {
                return ResourceManager.GetString("Filesystem_Config_FileSearchStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system.
        /// </summary>
        internal static string Filesystem_Config_Filesystem {
            get {
                return ResourceManager.GetString("Filesystem_Config_Filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Filesystem_Config_OK {
            get {
                return ResourceManager.GetString("Filesystem_Config_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute: {0}.
        /// </summary>
        internal static string Filesystem_Message_CannotExecute {
            get {
                return ResourceManager.GetString("Filesystem_Message_CannotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesystem.
        /// </summary>
        internal static string Filesystem_ModuleDisplayName {
            get {
                return ResourceManager.GetString("Filesystem_ModuleDisplayName", resourceCulture);
            }
        }
    }
}
