//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSearchModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSearchModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevDocs.io.
        /// </summary>
        internal static string WebSearch_DevDocs {
            get {
                return ResourceManager.GetString("WebSearch_DevDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on DevDocs.io.
        /// </summary>
        internal static string WebSearch_DevDocs_Comment {
            get {
                return ResourceManager.GetString("WebSearch_DevDocs_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string WebSearch_Google {
            get {
                return ResourceManager.GetString("WebSearch_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with Google.
        /// </summary>
        internal static string WebSearch_Google_Comment {
            get {
                return ResourceManager.GetString("WebSearch_Google_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        internal static string WebSearch_GoogleMaps {
            get {
                return ResourceManager.GetString("WebSearch_GoogleMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on Google Maps.
        /// </summary>
        internal static string WebSearch_GoogleMaps_Comment {
            get {
                return ResourceManager.GetString("WebSearch_GoogleMaps_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web search.
        /// </summary>
        internal static string WebSearch_ModuleDisplayName {
            get {
                return ResourceManager.GetString("WebSearch_ModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSDN.
        /// </summary>
        internal static string WebSearch_MSDN {
            get {
                return ResourceManager.GetString("WebSearch_MSDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on MSDN.
        /// </summary>
        internal static string WebSearch_MSDN_Comment {
            get {
                return ResourceManager.GetString("WebSearch_MSDN_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackOverflow.
        /// </summary>
        internal static string WebSearch_StackOverflow {
            get {
                return ResourceManager.GetString("WebSearch_StackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on StackOverflow.
        /// </summary>
        internal static string WebSearch_StackOverflow_Comment {
            get {
                return ResourceManager.GetString("WebSearch_StackOverflow_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia.
        /// </summary>
        internal static string WebSearch_Wikipedia {
            get {
                return ResourceManager.GetString("WebSearch_Wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on Wikipedia.
        /// </summary>
        internal static string WebSearch_Wikipedia_Comment {
            get {
                return ResourceManager.GetString("WebSearch_Wikipedia_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        internal static string WebSearch_Youtube {
            get {
                return ResourceManager.GetString("WebSearch_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on Youtube.
        /// </summary>
        internal static string WebSearch_Youtube_Comment {
            get {
                return ResourceManager.GetString("WebSearch_Youtube_Comment", resourceCulture);
            }
        }
    }
}
