//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer power commands.
        /// </summary>
        internal static string Power_ActionComment {
            get {
                return ResourceManager.GetString("Power_ActionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power_ActionDisplayName {
            get {
                return ResourceManager.GetString("Power_ActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string Power_Hibernate {
            get {
                return ResourceManager.GetString("Power_Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernates current Windows session and shuts down the computer..
        /// </summary>
        internal static string Power_Hibernate_Comment {
            get {
                return ResourceManager.GetString("Power_Hibernate_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string Power_Lock {
            get {
                return ResourceManager.GetString("Power_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks the current session.
        /// </summary>
        internal static string Power_Lock_Comment {
            get {
                return ResourceManager.GetString("Power_Lock_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string Power_LogOff {
            get {
                return ResourceManager.GetString("Power_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs off current user.
        /// </summary>
        internal static string Power_LogOff_Comment {
            get {
                return ResourceManager.GetString("Power_LogOff_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power_ModuleDisplayName {
            get {
                return ResourceManager.GetString("Power_ModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Power_Reboot {
            get {
                return ResourceManager.GetString("Power_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes Windows and reboots the computer..
        /// </summary>
        internal static string Power_Reboot_Comment {
            get {
                return ResourceManager.GetString("Power_Reboot_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Power_Shutdown {
            get {
                return ResourceManager.GetString("Power_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes Windows and shuts down the computer..
        /// </summary>
        internal static string Power_Shutdown_Comment {
            get {
                return ResourceManager.GetString("Power_Shutdown_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Power_Sleep {
            get {
                return ResourceManager.GetString("Power_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puts computer in the suspended state..
        /// </summary>
        internal static string Power_Sleep_Comment {
            get {
                return ResourceManager.GetString("Power_Sleep_Comment", resourceCulture);
            }
        }
    }
}
