//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCommandsModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomCommandsModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CustomCommands_Config_Add {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string CustomCommands_Config_Command {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following special strings:.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp1 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp10 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert plain {, and.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp11 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }}.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp12 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert plain }..
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp13 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp2 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert first parameter of command. Use {1}, {2}, ... to insert next parameters..
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp3 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {u0}.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp4 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert first URL-encoded parameter of command..
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp5 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {*}.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp6 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert whole parameter text.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp7 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {u*}.
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp8 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - to insert whole URL-encoded parameter text..
        /// </summary>
        internal static string CustomCommands_Config_CommandHelp9 {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CommandHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CustomCommands_Config_Comment {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom commands.
        /// </summary>
        internal static string CustomCommands_Config_CustomCommands {
            get {
                return ResourceManager.GetString("CustomCommands_Config_CustomCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CustomCommands_Config_Delete {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string CustomCommands_Config_Key {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string CustomCommands_Config_Kind {
            get {
                return ResourceManager.GetString("CustomCommands_Config_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CustomCommands_Config_OK {
            get {
                return ResourceManager.GetString("CustomCommands_Config_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result command:.
        /// </summary>
        internal static string CustomCommands_Config_ResultCommand {
            get {
                return ResourceManager.GetString("CustomCommands_Config_ResultCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test input:.
        /// </summary>
        internal static string CustomCommands_Config_TestInput {
            get {
                return ResourceManager.GetString("CustomCommands_Config_TestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstParameter &amp;quot;Second parameter with spaces and &amp;quot;&amp;quot;quotes&amp;quot;&amp;quot;&amp;quot;.
        /// </summary>
        internal static string CustomCommands_Config_TestInput_Default {
            get {
                return ResourceManager.GetString("CustomCommands_Config_TestInput_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute: {0}.
        /// </summary>
        internal static string CustomCommands_Message_CannotExecute {
            get {
                return ResourceManager.GetString("CustomCommands_Message_CannotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom command keys cannot contain space characters!.
        /// </summary>
        internal static string CustomCommands_Message_CustomCommandKeysCannotContainSpaceCharacters {
            get {
                return ResourceManager.GetString("CustomCommands_Message_CustomCommandKeysCannotContainSpaceCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom command keys must be unique!.
        /// </summary>
        internal static string CustomCommands_Message_CustomCommandKeysMustBeUnique {
            get {
                return ResourceManager.GetString("CustomCommands_Message_CustomCommandKeysMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomCommands_ModuleDisplayName {
            get {
                return ResourceManager.GetString("CustomCommands_ModuleDisplayName", resourceCulture);
            }
        }
    }
}
